-- Catalog metadata in English (the app UI is English) and product image galleries.

alter table public.productos add column imagenes text[] not null default '{}';

update public.categorias set nombre_categoria = 'Electronics' where nombre_categoria = 'Tecnología';
update public.categorias set nombre_categoria = 'Home' where nombre_categoria = 'Hogar';
update public.categorias set nombre_categoria = 'Fashion' where nombre_categoria = 'Moda';
update public.categorias set nombre_categoria = 'Beauty' where nombre_categoria = 'Belleza';
update public.categorias set nombre_categoria = 'Sports' where nombre_categoria = 'Deportes';
update public.categorias set nombre_categoria = 'Accessories' where nombre_categoria = 'Accesorios';

update public.atributos_producto set nombre_atributo = 'Brand' where nombre_atributo = 'Marca';
update public.atributos_producto set nombre_atributo = 'Weight' where nombre_atributo = 'Peso';
update public.atributos_producto set nombre_atributo = 'Warranty' where nombre_atributo = 'Garantía';

-- Galleries for the demo catalog (matched by product name).
update public.productos p
set imagenes = g.imagenes
from (values
  ('iPhone 5s', array['https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/1.webp', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/2.webp', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/3.webp']::text[]),
  ('Apple MacBook Pro 14 Inch Space Grey', array['https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp', 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp', 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp']::text[]),
  ('iPad Mini 2021 Starlight', array['https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/1.webp', 'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/2.webp', 'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/3.webp', 'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/4.webp']::text[]),
  ('Amazon Echo Plus', array['https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/1.webp', 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/2.webp']::text[]),
  ('iPhone 6', array['https://cdn.dummyjson.com/product-images/smartphones/iphone-6/1.webp', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/2.webp', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/3.webp']::text[]),
  ('Asus Zenbook Pro Dual Screen Laptop', array['https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp', 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp', 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp']::text[]),
  ('Samsung Galaxy Tab S8 Plus Grey', array['https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/1.webp', 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/2.webp', 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/3.webp', 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/4.webp']::text[]),
  ('Apple Airpods', array['https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/1.webp', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/2.webp', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/3.webp']::text[]),
  ('Annibale Colombo Bed', array['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp']::text[]),
  ('Decoration Swing', array['https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/1.webp', 'https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/2.webp', 'https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/3.webp']::text[]),
  ('Bamboo Spatula', array['https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/1.webp']::text[]),
  ('Annibale Colombo Sofa', array['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp']::text[]),
  ('Family Tree Photo Frame', array['https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/1.webp']::text[]),
  ('Black Aluminium Cup', array['https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/1.webp', 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/2.webp']::text[]),
  ('Bedside Table African Cherry', array['https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp', 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp', 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp']::text[]),
  ('House Showpiece Plant', array['https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/1.webp', 'https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/2.webp', 'https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/3.webp']::text[]),
  ('Blue & Black Check Shirt', array['https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp', 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp', 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp', 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp']::text[]),
  ('Blue Frock', array['https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp', 'https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp', 'https://cdn.dummyjson.com/product-images/tops/blue-frock/3.webp', 'https://cdn.dummyjson.com/product-images/tops/blue-frock/4.webp']::text[]),
  ('Black Women''s Gown', array['https://cdn.dummyjson.com/product-images/womens-dresses/black-women''s-gown/1.webp', 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women''s-gown/2.webp', 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women''s-gown/3.webp', 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women''s-gown/4.webp']::text[]),
  ('Nike Air Jordan 1 Red And Black', array['https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp', 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp', 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/3.webp', 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/4.webp']::text[]),
  ('Black & Brown Slipper', array['https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/1.webp', 'https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/2.webp', 'https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/3.webp', 'https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/4.webp']::text[]),
  ('Blue Women''s Handbag', array['https://cdn.dummyjson.com/product-images/womens-bags/blue-women''s-handbag/1.webp', 'https://cdn.dummyjson.com/product-images/womens-bags/blue-women''s-handbag/2.webp', 'https://cdn.dummyjson.com/product-images/womens-bags/blue-women''s-handbag/3.webp']::text[]),
  ('Gigabyte Aorus Men Tshirt', array['https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp', 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp', 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp', 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/4.webp']::text[]),
  ('Girl Summer Dress', array['https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp', 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp', 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/3.webp', 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/4.webp']::text[]),
  ('Essence Mascara Lash Princess', array['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp']::text[]),
  ('Calvin Klein CK One', array['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp']::text[]),
  ('Attitude Super Leaves Hand Soap', array['https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/1.webp', 'https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/2.webp', 'https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/3.webp']::text[]),
  ('Eyeshadow Palette with Mirror', array['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp']::text[]),
  ('Chanel Coco Noir Eau De', array['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp']::text[]),
  ('Olay Ultra Moisture Shea Butter Body Wash', array['https://cdn.dummyjson.com/product-images/skin-care/olay-ultra-moisture-shea-butter-body-wash/1.webp', 'https://cdn.dummyjson.com/product-images/skin-care/olay-ultra-moisture-shea-butter-body-wash/2.webp', 'https://cdn.dummyjson.com/product-images/skin-care/olay-ultra-moisture-shea-butter-body-wash/3.webp']::text[]),
  ('Powder Canister', array['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp']::text[]),
  ('Dior J''adore', array['https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/3.webp']::text[]),
  ('American Football', array['https://cdn.dummyjson.com/product-images/sports-accessories/american-football/1.webp']::text[]),
  ('Baseball Ball', array['https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/1.webp']::text[]),
  ('Baseball Glove', array['https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/1.webp', 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/2.webp', 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/3.webp']::text[]),
  ('Basketball', array['https://cdn.dummyjson.com/product-images/sports-accessories/basketball/1.webp']::text[]),
  ('Basketball Rim', array['https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/1.webp']::text[]),
  ('Cricket Ball', array['https://cdn.dummyjson.com/product-images/sports-accessories/cricket-ball/1.webp']::text[]),
  ('Cricket Bat', array['https://cdn.dummyjson.com/product-images/sports-accessories/cricket-bat/1.webp']::text[]),
  ('Cricket Helmet', array['https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/1.webp', 'https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/2.webp', 'https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/3.webp', 'https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/4.webp']::text[]),
  ('Brown Leather Belt Watch', array['https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/1.webp', 'https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/2.webp', 'https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/3.webp']::text[]),
  ('IWC Ingenieur Automatic Steel', array['https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/1.webp', 'https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/2.webp', 'https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/3.webp']::text[]),
  ('Black Sun Glasses', array['https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/1.webp', 'https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/2.webp', 'https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/3.webp']::text[]),
  ('Green Crystal Earring', array['https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/1.webp', 'https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/2.webp', 'https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/3.webp']::text[]),
  ('Longines Master Collection', array['https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/1.webp', 'https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/2.webp', 'https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/3.webp']::text[]),
  ('Rolex Cellini Moonphase', array['https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/1.webp', 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/2.webp', 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/3.webp']::text[]),
  ('Classic Sun Glasses', array['https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/1.webp', 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/2.webp', 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/3.webp']::text[]),
  ('Green Oval Earring', array['https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/1.webp', 'https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/2.webp', 'https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/3.webp']::text[])
) as g (nombre_producto, imagenes)
where p.nombre_producto = g.nombre_producto;
